graphql-nexus/nexus

- docs/getting-started.md
- docs/type-generation.md
- examples/apollo-fullstack/src/fullstack-typegen.ts
- examples/apollo-fullstack/src/schema/query.ts
- examples/githunt-api/githunt-api-schema.graphql
- examples/githunt-api/src/githunt-typegen.ts
- examples/githunt-api/src/schema.js
- examples/kitchen-sink/kitchen-sink-schema.graphql
- examples/kitchen-sink/src/definitions.ts
- examples/kitchen-sink/src/kitchen-sink-typegen.ts
- examples/kitchen-sink/tsconfig.json
- examples/star-wars/src/graphql/character.ts
- examples/star-wars/src/graphql/human.ts
- examples/star-wars/src/star-wars-typegen.ts
- examples/star-wars/src/types/backingTypes.ts
- examples/ts-ast-reader/src/ts-ast-reader-typegen.ts
- examples/ts-ast-reader/src/types/interfaces.ts
- package.json
- src/builder.ts
- src/core.ts
- src/metadata.ts
- src/typegen.ts
- src/types.ts
- src/utils.ts
- website/pages/playground.html
- website/siteConfig.js
Adds support for inline resolver signature. Removes `property` option, use inline resolver instead:
```ts
t.int('id', o => o.id_field)
// alias for:
t.int('id', { resolve: o => o.id_field })
```
Enforces type-safety around resolver or default is implemented when not backed by model value fulfilling the correct signature of the field (complete type-safety).
cc @schickling
> Inline resolver, full-type safety on fields

- src/sdlConverter.ts
- tests/sdlConverter.spec.ts
Exported files by sdlConverter with `commonjs: true` option cause ReferenceError like below.
```
 $  yarn start
yarn run v1.10.1
$ node lib/index.js
/Users/moriwakikento/.ghq/github.com/KentoMoriwaki/grgr/generated/project_server-types.js:40
t.list.field("staffings", { type: Staffing })
^
ReferenceError: Staffing is not defined
at Object.definition (/Users/moriwakikento/.ghq/github.com/KentoMoriwaki/grgr/generated/project_server-types.js:40:39)
at SchemaBuilder.buildObjectType (/Users/moriwakikento/.ghq/github.com/KentoMoriwaki/grgr/node_modules/nexus/dist/builder.js:159:16)
at SchemaBuilder.getOrBuildType (/Users/moriwakikento/.ghq/github.com/KentoMoriwaki/grgr/node_modules/nexus/dist/builder.js:513:29)
at /Users/moriwakikento/.ghq/github.com/KentoMoriwaki/grgr/node_modules/nexus/dist/bu …
```
> Fix sdlConverter to export as commonjs

- docs/api-makeSchema.md
- src/builder.ts
Hello,
Thank you for the great work with Nexus!
I have noticed that the docs state the opposite default value for `shouldGenerateArtifacts` as it is defined in the code:
https://github.com/prisma/nexus/blob/a6156ee8f46b2e525c24b849934a51e315f4ece1/src/builder.ts#L1012-L1014
> Fix docs for shouldGenerateArtifacts default

- src/typegenMetadata.ts
before this, if we specified a path to writing generated files that don't exist the file creation fails.
```
{ [Error: ENOENT: no such file or directory, open '[....removed]/src/graphql/schema/local/__generated__/schema.graphql']
errno: -2,
code: 'ENOENT',
syscall: 'open',
path:
'[....removed]/src/graphql/schema/local/__generated__/schema.graphql' }
```
> create folder path recursively if missing when generating files

- src/typegenAutoConfig.ts
Since the typegen import paths are resolved asynchronously, they add their config to `importsMap` in a non-deterministic order.  This means that when `Object.keys(importsMap)` is called, it's not guaranteed that the imports are returned in the same order, which in turn causes the generated file to sometimes re-shuffle imports.  This hampers the ability to check the generated files into version control, since the imports are occasionally re-ordered.
1. Have more than one file in `typegenAutoConfig.sources`:
```typescript
makeSchema({
...
typegenAutoConfig: {
// at least two source files here
sources: [
{
alias: 'one',
source: 'path/to/one',
},
{
alias: 'two',
source: 'path/to/two',
},
...
],
},
})
```
2. Run the app multiple times - the generated typegen file will sometimes import `one` …
> Prevent reordering generated imports by deterministically sorting by alias name

- docs/library-authors.md
- website/core/Footer.js
+ Update playground url to prevent that if you're on `docs` and click on `playground` the url is going to be `https://nexus.js.org/docs/playground`
+ Replace `./nexus` for `nexus` to follow the same order on all the docs.
> Update playground url

- src/definitions/args.ts
This allows you to pass a `NexusWrappedType` instance as an argument for type when using `arg({ type: ... })` utility to define an argument for a type.
Ex: 
```
import MyType from './MyType'
const MyOtherType = queryField('name', {
args: { myType: arg({ type: MyType }) } 
})
```
The feature actually works as is, the type is incorrect though.
> Extract reusable type for the "type" option

- src/typegenAutoConfig.ts
The `typeGenAutoConfig` currently generates invalid import paths containing non-escaped backslashes if run on Windows.
This PR fixes that by using a regex that replaces every backslash with a forward slash.
Fix #41
> Fix import path generation on Windows

- package.json
- src/sdlConverter.ts
- tests/_sdl.ts
- tests/sdlConverter.spec.ts
- tests/typegen.spec.ts
- yarn.lock
This fixes the SDL converter for lists with a depth of 1 with nullable members. 
Need to add docs for this, but `list: boolean[]` is the syntax for lists with configurable depth/nullability.
These two are equivalent:
```ts
t.string('someField', { list: true }) // someField: [String!]!
t.list.string('someField') // someField: [String!]! 
```
When you have nullable items:
```ts
t.string('someField', { list: [false] }) // someField: [String]!
```
For nested lists:
```ts
t.string('someField', { list: [false, true] }) // someField: [[String]!]!
t.string('someField', { list: [true, true] }) // someField: [[String!]!]!
```
> Fix #89, SDL converter & list w/ nested varying null items

- docs/database-access-with-prisma.md
Hello there :wave:,
After following the getting started on Nexus with Prisma, i found a little typo [here](https://nexus.js.org/docs/database-access-with-prisma#expose-full-crud-graphql-api).
> [docs]: fix definition methods typo on prismaObjectType()

- docs/library-authors.md
There were some syntax and scope issues on the example.
This should fix it.
(the code wouldn't without this fix, there were mismatched braces)
It would be nice to run prettier on the markdown, it can catch some of this bugs (: and provides a more consistent style throughout the docs
> Fix library authors example's syntax issue

- docs/api-args.md
This PR includes documentation that came directly from `/nexus/src/definitions/args.ts`.
> Add documentation for arg options

- src/definitions/subscriptionField.ts
With this PR I'm adding the ability to return a promise in the `subscribe` function and should make it possible to return the entire `SubscriptionPayload` of Prisma.
I can also provide an example if you want...
Fixes #119
> Add promise support to subscriptions

- docs/database-access-with-prisma.md
Fix a small typo in `database-access-with-prisma.md`.
> Fix small typo in database-access-with-prisma.md

- docs/api-scalarType.md
When I started with Nexus I had to find how to declare Upload and DateTime. It should be defined in the docs. Feel free to update it as you want.
> Add scalar examplex (Upload, DateTime) for new users

- docs/getting-started.md
Added forgotten `enumType` import and used `args` over deprecated `fieldArg`
> Fix mistakes in "Example Schema" of getting started

- src/definitions/subscriptionField.ts
- tests/backingTypes.spec.ts
> Fix wrong fieldName type on subscriptionField (and fix backingTypes.spec.ts)

- src/builder.ts
- tests/resolveTypes.spec.ts
- website/i18n/en.json
You can check the issue [here](https://nexus.js.org/playground).
```js
t.date('updatedAt', () => new Date());
``` 
is not working as expected, as it is right now it only works with:
```js
t.field('updatedAt', {
type: 'Date',
resolve: () => new Date()
});
```
> Fix inline functions for custom scalars

- src/builder.ts
- src/definitions/_types.ts
- src/definitions/wrapping.ts
- src/dynamicProperty.ts
- src/index.ts
This change addresses the last thing remaining in the way before `nexus-prisma` can get back on the nexus mainline.
https://github.com/prisma/nexus-prisma/issues/304
> fix: dynamic output property

- .circleci/config.yml
- jest.config.js
- package.json
- src/definitions/definitionBlocks.ts
- src/typegen.ts
- src/typegenTypeHelpers.ts
- tests/__snapshots__/backingTypes.spec.ts.snap
- tests/__snapshots__/typegen.spec.ts.snap
- tests/integration/_s.ts
- tests/integration/_s.typegen.ts
- tests/integration/_xs.typegen.ts
- yarn.lock
https://github.com/prisma/nexus-prisma/issues/367#issuecomment-526882555
Will fix prisma/nexus-prisma#367
Will unblock https://github.com/prisma/nexus-prisma/pull/368
> fix: typegen for dynamicOutputProperty

- src/utils.ts
The absolute path error was driving me nuts, as I thought it was telling me my string was not a string. I've updated the error message to correctly communicate the error.
> Correct error message about absolute paths

- package.json
- tests/integration/_helpers.ts
- tests/integration/_s.typegen.ts
- tests/integration/_xs.typegen.ts
- tests/tsconfig.json
- yarn.lock
This was really slowing down yarn install locally, because it seemed to be linking everything in `node_modules` recursively or something. This taps into the `formatTypegen` method to accomplish the same end-goal, testing the local `nexus` in the integration tests.
> Remove file:. from devDependencies

- README.md
Your CircleCI badge/shield was broken:
It's a tiny thing but when an employee is making the argument to use a library to their boss, 'broken' CI doesn't help their case
* Somewhat unnecessary, however replace your broken/outdated circleCI shield image. 
Generated from [ShieldsIO](https://shields.io/category/build) with the following config: 
* Spaced out the badges to new lines for a tiny bit of readability.
> docs: Update circleci badge link

- tests/tsconfig.json
- tsconfig.json
On my machine I get jest test matcher type errors. This PR fixes that. Its also just simpler and what I would expect in the first place.
Unless the original motivation for how it was remains, we should simplify.
> chore: simplify tsconfig

- src/builder.ts
- tests/builder.spec.ts
This can impact the end-user when they, for example, are using the `types` TS compiler option. In that situation, expressing a whitelist of TypeScript type-packages, in a Nexus app, it would be important that the user also include typegen or else TSC would stop seeing it (forcing the user to provide custom typegen config). To make it easier for users to do that, let them refer to a pretty name, rather than something hard to predict, remember, and looks ugly.
> feat(typegen): nicer generated package name

- README.md
- consistent with what we did in nexus-prisma
- consistent with Prisma's consolidate community touch points efforts
We could add badges to the slack community?
> docs: remove spectrum link

- src/typegenMetadata.ts
Pretty sure as it's written currently it is a potential race-condition because it's not awaiting the delete.
> fix(typegen): explicitly await removeFile before write

- codecov.yml
- package.json
We should only care that new lines of code added have coverage.
> chore(codecov): Only use codecov diff coverage

- src/definitions/definitionBlocks.ts
- tests/__snapshots__/inputObjectType.spec.ts.snap
- Updated warning message when specifying `.list` and `list: true` for `inputObject`
> refactor: Update warn message for inputObject

- src/plugins/connectionPlugin.ts
- src/typegenTypeHelpers.ts
- Fixing the typing on 'nodes' field
- Remove the `$` prefixed `never` types
- Add `MaybePromise` around `nodes` result
> fix: Connection type improvements

- src/builder.ts
- src/definitions/_types.ts
- src/plugins/fieldAuthorizePlugin.ts
- tests/plugins/__snapshots__/fieldAuthorizePlugin.spec.ts.snap
- tests/plugins/fieldAuthorizePlugin.spec.ts
This PR implements `name: string` to `fieldConfig` and improve error message in `fieldAuthorizePlugin` and update test snapshots
Fixes: #319
> feat: add name to fieldConfig

- package.json
- src/plugins/queryComplexityPlugin.ts
- yarn.lock
Turns out this import (only for the types) doesn't really give us much, so we can remove it.
> fix: remove graphql-query-complexity import, closes #376

- src/plugins/connectionPlugin.ts
This supports the transition https://github.com/prisma-labs/nexus/issues/373. It allows the @nexus/schema package to not have to branch code from nexus package.
> feat: respect manifest name in typegen imports

- src/typegenPrinter.ts
When using Windows, rootTypings paths are using `\` instead of `/` in generated code. This commit fixes it.
> fix: typegen stable path generation with Windows

- package.json
- src/plugins/connectionPlugin.ts
- tests/plugins/nullabilityGuardPlugin.spec.ts
- yarn.lock
One internal type error was raised with 3.9 that wasn't before.
This might have led to end-users having to enable `skipLibCheck`?
For my doubt on this, I'm leaning toward this being a feature, rather than just a chore.
> feat: support typescript 3.9

- src/definitions/scalarType.ts
- src/typegenPrinter.ts
- tests/__snapshots__/backingTypes.spec.ts.snap
- tests/__snapshots__/typegenPrinter.spec.ts.snap
- tests/integration/_app.typegen.ts
- tests/plugins/__snapshots__/fieldAuthorizePlugin.spec.ts.snap
- tests/plugins/__snapshots__/queryComplexityPlugin.spec.ts.snap
- tests/scalarType.spec.ts
- tests/typegen/types.gen.ts
fixes #469 
- Improve the general typing of custom scalars
- Create a new `NexusGenScalars` for all scalar types
- Remove scalars from `NexusGenRootTypes` (might be a breaking change, need review)
- Use the `NexusGenScalars` for all non specified (base GraphQL) scalars in `input` and `output` types
- Add `rootTyping` parameter to `asNexusMethod` to allow the user to specify it, otherwise it will fallback to the `backingTypeMap`
BREAKING CHANGE:
The global TS type `NexusGenRootTypes` no longer contains scalars. All scalars now live under a new global TS type named `NexusGenScalars`.
```ts
// before
let foo: NexusGenRootTypes['String']
```
```ts
// after
let foo: NexusGenScalars['String']
```
> feat: allow asNexusMethod to specify TS type

- docs/api-scalarType.md
The problem in #360 was the missing documentation on how to do it. Now that it's even easier with #473 so this PR updates the docs with an example.
> docs: update asNexusMethod example with the changes from #473

- src/builder.ts
- tests/__snapshots__/interfaceType.spec.ts.snap
This fixes a small mistake in the error message shown when `resolveType` hasn't been defined on an interfaceType.
> fix: message for missing resolveType in interfaces

- tmp/_redirects
This will serve as a temporary deploy folder for the old nexus.js.org until the DNS has been updated.
> temp: Temporary redirects for old nexus.js.org

- src/builder.ts
- src/definitions/_types.ts
- src/plugins/nullabilityGuardPlugin.ts
- tests/__snapshots__/definitions.spec.ts.snap
- tests/__snapshots__/makeSchema.spec.ts.snap
- tests/__snapshots__/plugin.spec.ts.snap
- tests/__snapshots__/plugins.spec.ts.snap
- tests/definitions.spec.ts
- tests/integration/_app.typegen.ts
- tests/plugins/__snapshots__/fieldAuthorizePlugin.spec.ts.snap
- tests/plugins/__snapshots__/queryComplexityPlugin.spec.ts.snap
- tests/plugins/fieldAuthorizePlugin.spec.ts
- tests/plugins/nullabilityGuardPlugin.spec.ts
- tests/subscriptionField.spec.ts
- tests/subscriptionType.spec.ts
This PR
- makes output types nullable by default
- makes list items nullable by default
> feat: output types & list items are now nullable by default 

- docs/content/040-adoption-guides/020-nexus-framework-users.mdx
It has been renamed: https://github.com/whitecolor/ts-node-dev/issues/186
> docs: Fix ts-node-dev flag in the docs

- docs/content/040-adoption-guides/030-neuxs-framework-prisma-users.mdx
typo with `nexus-plugin-prisma` and version `0.20.0` instead of `0.30`
> chore(docs): Fix a typo in 030-neuxs-framework-prisma-users.mdx

- .github/workflows/pull-request.yml
- .github/workflows/trunk.yml
- codecov.yml
- docs/content/015-api/110-plugins.mdx
- examples/kitchen-sink/src/example-plugins.ts
- examples/kitchen-sink/src/index.ts
- examples/kitchen-sink/src/kitchen-sink-definitions.ts
- examples/ts-ast-reader/ts-ast-reader-schema.graphql
- src/builder.ts
- src/plugin.ts
- tests/plugin.spec.ts
The `onObjectDefinition` plugin option allows for a plugin to declarative modify the definition of an object type.
For example:
```ts
const Post = objectType({
name: 'Post',
node: 'uuid',
resolve(t) {
t.string('name')
}
})
```
This allows the plugin to intercept the `t` (definition block builder) after the fields are applied, and based on the presence of `node` in the object definition, add: 
```ts
onObjectDefinition((t, config) => {
if (config.node) {
t.implements('Node')
t.id('id', { 
nullable: false,
resolve: (root, args, ctx, info) => `${info.parentType.name}:${root[config.node]}`
})
}
})
```
Also added `onInputObjectDefinition` for symmetry, but not sure if it'd be useful yet.
> feat: add onObjectDefinition / onInputObjectDefinition

- src/typegenPrinter.ts
- tests/__snapshots__/sdlConverter.spec.ts.snap
- tests/__snapshots__/typegenPrinter.spec.ts.snap
- tests/_sdl.ts
- tests/typegen/schema.gen.graphql
- tests/typegen/types.gen.ts
> fix: input fields with default should not be typed as optional

- src/typegenAutoConfig.ts
- src/typegenPrinter.ts
- tests/backingTypes.spec.ts
Closes #396
We unfortunately cannot add a runtime error if the type that's imported from the path does not exist without substantial work and/or performance overhead.
If we use the current regex approach, we might end up throwing in cases where the type is properly exported but the regex fails to see that.
The only approach would be to parse the actual file with the type-checker, which is way out of scope for this PR.
> fix: error if root typing path is invalid

- docs/content/030-pluginss/050-prisma/010-overview.mdx
Since version 0.20 the nexus framework is not supported anymore. The docs still reference the nexus framework in the docs.
> chore(docs): Remove references to nexus framework

- examples/zeit-typescript/package.json
- examples/zeit-typescript/yarn.lock
- jest.config.js
- src/definitions/definitionBlocks.ts
- src/definitions/extendType.ts
- src/definitions/subscriptionField.ts
- src/definitions/subscriptionType.ts
- src/utils.ts
- tests/integration/_app.ts
- tests/integration/_app.typegen.ts
- tests/plugin.spec.ts
- tests/plugins/nullabilityGuardPlugin.spec.ts
- tests/plugins/queryComplexityPlugin.spec.ts
- tests/subscriptionType.spec.ts
fixes #559
This takes another stab at implementing subscription type. It fixes multiple things.
- It no longer sub-classes from Object Type. This means we lose interface implements support. However this was never tested before and it is unclear its even a feature we want.
- It simplifies the field shorthand typings by removing the resolver shorthand param style. This style is unusable since subscribe config field is always needed anyways.
- It fixes field shorthand config which would fail when typegen was present. Specifically the subscribe field was not being recognized before.
Also
- It adds subscription type test cases to integration test. This way we capture the error that only happens when typegen is present.
> fix: subscription type static typings

- docs/content/010-getting-started/03-tutorial/06-chapter-5-persisting-data-via-prisma.mdx
For the types in `args` there was `schema.<type>` in all the blocks of code which raises an error. However it should be `stringArg` and `intArg` rather than `schema.stringArg` and `schema.intArg`
> Update code blocks in Chapter 6 of the tutorial to fix error

- docs/content/030-pluginss/04-nullability-guard.mdx
onNullGuarded does not exist on `"@nexus/schema": "^0.16.0",`.
Btw the testing is failing because I need some API keys I think.
> chore(docs): fix nullabillity guard docs

- docs/content/015-api/011-subscription-type.mdx
- docs/content/015-api/101-subscription-field.mdx
- src/definitions/subscriptionField.ts
- src/definitions/subscriptionType.ts
closes #157
Certain things we cannot document yet because of bugs:
- https://github.com/graphql-nexus/schema/issues/594
- https://github.com/graphql-nexus/schema/issues/595
> chore(docs): document subscription type

- src/builder.ts
- src/plugins/connectionPlugin.ts
- tests/__snapshots__/nonNullDefaults.spec.ts.snap
- tests/nonNullDefaults.spec.ts
- tests/typegenPrinter.spec.ts
Fixes #588 by ensuring that list items follow `nonNullDefaults`, which was lost in the #508 refactor
Fixes #384 by removing explicit nullability config from the connection `edges` definition, and also allowing `nonNullDefaults` to be supplied for the connection "types" generated by the creation of a connection field. Allows you to configure both globally in the connection plugin field config, and when the connection field is defined.
> fix: #588, #384 non-null list items & connection nullability

- src/typegenPrinter.ts
- src/utils.ts
- tests/scalarType.spec.ts
Previously, when specifying `rootTyping.path`, on a scalar it needed to be an absolute path. 
This allows you to instead specify a named `node_module`, which is often more useful in monorepo type projects.
> feat: Allow specifying a node module for type imports

- examples/apollo-fullstack/src/schema/launch.ts
- examples/kitchen-sink/package.json
- examples/kitchen-sink/src/kitchen-sink-definitions.ts
- examples/ts-ast-reader/package.json
- examples/ts-ast-reader/src/types/interfaces.ts
- src/definitions/definitionBlocks.ts
- tests/__helpers/helpers.ts
- tests/backingTypes.spec.ts
- tests/integrations/kitchenSink/__app.ts
- tests/plugins/connectionPlugin.spec.ts
- tests/typegen/types.gen.ts
- tests/unionType.spec.ts
closes #582
As discussed. In most cases resolver shorthands are not a serious use of the API.
BREAKING CHANGE:
Resolver shorthand API is now removed. The following will now not typecheck:
```ts
t.string('foo', () => ... )
```
Instead use:
```ts
t.string('foo', { resolve: () => ... })
```
Runtime support is still intact but will result in a logged warning. Runtime support will be removed in the next Nexus release.
--- 
I probably missed areas of the codebase that can be simplified as a result. In particular the parts in the builder module that need to do runtime checks. Also maybe something about typegen?
> improve: remove resolver shorthands

- docs/content/014-guides/021-abstract-types.mdx
> It is based on supplying at `__tpename` field 
Has been corrected to
> It is based on supplying at `__typename` field
> chore(docs): fix little typo in 021-abstract-types.mdx

- src/plugins/index.ts
- tests/plugin.spec.ts
Noticed a bunch of things were showing up on the top-level API because of `export *` for various plugins.
We want to group these things under namespaces and keep the top level API clean when we can.
> chore: Refine exports for plugins

- docs/content/index.mdx
- package.json
- yarn.lock
closes #580
Basically we now say they should use TS 4.1. And in the future we'll force that without introducing a breaking change... I guess. 😕 
It seems pedantic but we could apply a TS 4.1 feature somewhere just to force the upgrade and avoid confusion later. E.g.:
```ts
type Foobar = 'hello'
type ForceTS41 = `${Foobar} World`
```
> deps: update to latest

- src/builder.ts
- src/typegenMetadata.ts
- src/typegenUtils.ts
- tests/backingTypes.spec.ts
- tests/interfaceType.spec.ts
- tests/makeSchema.spec.ts
closes #632
BREAKING CHANGE:
SDL file generation will be enabled by default in development now.
If you were enabling it manually before and outputting to project root at `schema.graphql` You can probably now just rely on the default.
If you were relying on the default to disable SDL file generation before then now you need to pass an explicit false:
```ts
makeSchema({
outputs: {
schema: false
}
})
```
> feat(config): SDL file generation by default in development

- docs/content/015-api/020-union-type.mdx
- src/builder.ts
- src/definitions/interfaceType.ts
- src/definitions/unionType.ts
- src/definitions/wrapping.ts
- src/messages.ts
- src/plugins/declarativeWrapping.ts
- tests/null-list.spec.ts
- tests/plugins/declarativeWrapping.spec.ts
- tests/wrapping.spec.ts
- Don't worry if we use both chaining & wrapping, they should be able to co-exist just fine
- Previously `list: true, nullable: false` would lead to -> `[Type!]!`, this enables that in the `declarativeWrapping` plugin
- Add a warning message w/ links to the `t.resolveType` usages
> chore: resolveType warning, restore declarativeWrapping list behavior

- src/builder.ts
- tests/interfaceType.spec.ts
The dynamic output members weren't being added during the walk phase of the new interfaces implementing interfaces feature.
> fix: Fix #622, custom scalars should work with interfaceType

- src/builder.ts
- src/definitions/list.ts
- src/definitions/nonNull.ts
- src/definitions/nullable.ts
- tests/modify.spec.ts
Test included. Might try to clean this stuff up further at some point.
> fix: Ensure we can modify nullability of an interface field

- src/definitions/extendInputType.ts
- src/definitions/inputObjectType.ts
- src/dynamicMethod.ts
- src/plugins/connectionPlugin.ts
- src/typegenPrinter.ts
- tests/dynamicMethods.spec.ts
- tests/integrations/kitchenSink/__app.ts
- tests/integrations/kitchenSink/__typegen.ts
- tests/plugins/__snapshots__/connectionPlugin.spec.ts.snap
- tests/plugins/connectionPlugin.spec.ts
Thought it'd be nice to be able to include documentation strings alongside dynamic methods, such as for the `connectionField`. Figured this might be useful for the stuff y'all are doing with the Prisma plugin too.
> feat: Improved description for types on output method / output field

- docs/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
I am getting start with tutorial.
and I found something wrong typo.
```
t.nonNull.field("createDraft", {...})
```
then, generated SDL as
```
createDraft(body: String!, title: String!): Post!
```
and
```
t.nonNull.list.field("drafts", {...}) => drafts: [Post]!
...
t.list.field("posts", { ...}}  => posts: [Post]
```
> chore(docs): tutorial typo nullable schema defined

- src/plugins/connectionPlugin.ts
- tests/integrations/kitchenSink/__app.ts
- tests/integrations/kitchenSink/__typegen.ts
- tests/plugins/__snapshots__/connectionPlugin.spec.ts.snap
- tests/plugins/connectionPlugin.spec.ts
Fix: #450 custom edge fields are not being resolved
feat: #515 allow connection plugin cursor to be non-string type
feat: #399, add requireResolver: false to skip requiring global extension fields
feat: #479, allow promise to be returned from pageInfoFromNodes
feat: #456, export connection plugin args
> feat: Connection plugin features & fixes

- docs/content/010-getting-started/03-tutorial/06-chapter-5-persisting-data-via-prisma.mdx
- docs/content/010-getting-started/03-tutorial/07-chapter-6-testing-with-prisma.mdx
- Use the Prisma Client created in `db.ts` in the API Context
- Disconnect Prisma Client after running each test, allowing Jest to exit. Previously this was an issue as the Prisma Client connection was never closed and prevented Jest from exiting. This issue was fixed in [`a9ca189`](https://github.com/graphql-nexus/tutorial/commit/8bcbe015fa1779770caa6b9dbcce67d000ba5c9c) using a workaround by passing the `--forceExit` flag to Jest.
This PR adds a proper fix for #678
> chore(docs): update tutorial testing chapter

- docs/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
- docs/content/010-getting-started/03-tutorial/06-chapter-5-persisting-data-via-prisma.mdx
- Use a JS object to store the GraphQL resolver context instead of a function that returns the object.
> chore(docs): use plain JS objects for storing the context

- docs/content/010-getting-started/04-why-nexus.mdx
As mentioned in #585
These are some of the benefits that I mentioned.
I think most of the gist of the initial issue is now in the docs. I extended the section with what I personally think are two of the major benefits of going to a Code first approach and especially using Nexus:
- The instant feedback loop
- The reduce repetitive work
The one thing which I think still deserves a highlight is the "endless" possibilities with plugins. I tried to hint at it in the context of repetitive work but in fact plugins can do way more. But I wasn't sure on how to fit it in or word it properly.
> chore(docs): add feedback loop and code re-use to Why Nexus

- docs/content/030-plugins/050-prisma/010-overview.mdx
Prisma tool changed syntax
```bash
$ yarn prisma -v
@prisma/cli          : 2.13.1
$ yarn prisma migrate --help
Update the database schema with migrations
WARNING Prisma's migration functionality is currently in Preview (https://pris.ly/d/preview).
When using any of the commands below you need to explicitly opt-in via the --preview-feature flag.
Usage
$ prisma migrate [command] [options] --preview-feature
Commands for development
dev   Create a migration from changes in Prisma schema, apply it to the database
trigger generators (e.g. Prisma Client)
reset   Reset your database and apply all migrations, all data will be lost
Commands for production/staging
deploy   Apply pending migrations to the database 
status   Check the status of your database migrations
resolve   Resolve issues with …
```
> chore(docs): Update 010-overview.mdx

- docs/content/010-getting-started/03-tutorial/07-chapter-6-testing-with-prisma.mdx
current implementation `prisma migrate up --create-db --experimental` throws the following error:
```
Command failed: /Users/canrozanes/Projects/ikiler-file-manager/node_modules/.bin/prisma migrate up --create-db --experimental
Error: The current command "up" doesn't exist in the new version of Prisma Migrate.
Read more about how to upgrade: https://pris.ly/d/migrate-upgrade
```
Changing the command to `prisma migrate dev --preview-feature` fixes the problem and runs the tests and passes them.
> fix(docs): update 07-chapter-6-testing-with-prisma.mdx

- docs/content/030-plugins/050-prisma/010-overview.mdx
Current one 404s! I _think_ this is where it is meant to point..please do check.
> chore(docs): fix docs overview link 404ing to repo examples

- docs/content/014-guides/025-abstract-types.mdx
Fix docs for abstract types to work with Typescript. With unions, it's not possible to use properties that are not intersections between these types. We can use `in` operator to have it working with Typescript.
> chore(docs): fix examples for abstract types to work with Typescript

- docs/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
Address the error "Property 'export' is missing in type '{ module: string; alias: string; }' but required in type 'TypingImport'.ts(2741)"
> chore(docs): Fix missing export

- docs/content/030-plugins/050-prisma/030-api.mdx
Updates the documentation of nexus-plugin-prisma to include the nexus common field config. These options will now be officially supported as of https://github.com/graphql-nexus/nexus-plugin-prisma/pull/989
> feat: Add docs for common field config of nexus-plugin-prisma

- docs/content/030-plugins/01-connection.mdx
- src/plugins/connectionPlugin.ts
- tests/plugins/__snapshots__/connectionPlugin.spec.ts.snap
- tests/plugins/connectionPlugin.spec.ts
Adds a getConnectionName and getEdgeName option to both the global
plugin config as well as the field config for the Relay Connection
plugin. This gives the user the ability to control the names of the
generated connection and edge types in the schema.
Closes #697
Prettier seems to have re-formatted some comments. I can remove these changes or put them in a separate commit if needed. Also, please let me know if the option descriptions and the tests are acceptable.
cc: @tgriesser
> feat: Add custom name options to Relay Connection plugin

- docs/content/030-plugins/050-prisma/010-overview.mdx
@jasonkuhrt Remove the [plugin settings section](https://nexusjs.org/docs/plugins/prisma/overview#plugin-settings) entirely. It contains more deprecated code like using `client` property which is now replaced by `prismaClient` of type `PrismaClientFetcher`
In addition, It's already covered in [configuration section](https://nexusjs.org/docs/plugins/prisma/overview#configuration) above.
> chore(docs): remove outdated prisma plugin config docs

- docs/content/010-getting-started/03-tutorial/03-chapter-2-writing-your-first-schema.mdx
- docs/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
1. Code and diff tabs code don't match
2. This is the first appearance of `stringArg`, it's never used before.
3. Display SDL code in a tab (same manner as the existing code below)
> docs: fix code example

- src/builder.ts
- src/definitions/extendType.ts
- tests/__snapshots__/interfaceType.spec.ts.snap
- tests/interfaceType.spec.ts
to fix #773 
Allow implementing interfaces in `extendType` definition
> feat: allow implementing interfaces in extendType

- src/definitions/inputObjectType.ts
- src/plugin.ts
- src/typegenPrinter.ts
- src/typegenTypeHelpers.ts
- tests/__snapshots__/backingTypes.spec.ts.snap
- tests/__snapshots__/typegenPrinter.spec.ts.snap
- tests/integrations/abstractTypes/allStrategiesOptionalWhenTypeNameEnabled/__typegen.ts
- tests/integrations/abstractTypes/isTypeOfsImplemented/__typegen.ts
- tests/integrations/abstractTypes/missingIsTypeOf/__typegen.ts
- tests/integrations/abstractTypes/missingResolveType/__typegen.ts
- tests/integrations/abstractTypes/missingResolveTypeOrIsTypeOf/__typegen.ts
- tests/integrations/abstractTypes/missingTypenameDiscriminant/__typegen.ts
- tests/integrations/abstractTypes/resolveTypeImplemented/__typegen.ts
- tests/integrations/declarativeWrappingPlugin/__typegen.ts
- tests/integrations/kitchenSink/__typegen.ts
- tests/integrations/unionTooComplexToRepresent/__typegen.ts
- tests/plugin.spec.ts
- tests/plugins/__snapshots__/fieldAuthorizePlugin.spec.ts.snap
- tests/plugins/__snapshots__/queryComplexityPlugin.spec.ts.snap
- tests/typegen/types.gen.ts
There's currently no way of extending `inputObjectType` through a plugin like we can do with `objectType`. I'm writing a validation plugin and [I need to "hook in" to the type for input objects](https://github.com/filipstefansson/nexus-validate/pull/9).
I copied the implementation for `NexusGenPluginTypeConfig` and renamed it to `NexusGenPluginInputTypeConfig`.
```ts
// my-plugin.ts
const inputObjectdDefTypes = printedGenTyping({
name: 'pluginName',
type: 'string',
...
});
const myPlugin = () => {
return plugin({
...
inputObjectTypeDefTypes: inputObjectdDefTypes,
});
}
```
```ts
// schema.ts
const MyInput = inputObjectType({
...
pluginName: 'hello world',
});
```
Let me know if this is relevant and if my solution works!
> feat: add plugin support for inputObjectType

- src/plugins/connectionPlugin.ts
- tests/plugins/connectionPlugin.spec.ts
- Adds `(root, ctx)` to `validateArgs`
- Iterate all nodes if neither `first` or `last` are provided, e.g. with custom `validateArgs`
- Export additional internal fns on `connectionPlugin`
> feat: connectionPlugin internal modifications

- src/plugins/connectionPlugin.ts
- tests/integrations/kitchenSink/__app.ts
- tests/integrations/kitchenSink/__schema.graphql
- tests/integrations/kitchenSink/__typegen.ts
- tests/plugins/connectionPlugin.spec.ts
The current functionality is useless as-is, because presumably you need to know the "source" value for an extended connection resolver in order to have the proper context to resolve it. Adds a fix, so the extended resolvers work similar to the `nodes` field and receive the source as the first value.
If anyone has issues with this, we can revert and make this opt-in, but this was the original intended behavior for extended connection fields, it just wasn't implemented correctly.
> fix: pass down source into extended connection fields

- src/plugins/connectionPlugin.ts
- tests/plugins/connectionPlugin.spec.ts
Fixes #813 - also ensures args are consistent between `nodes` & global extension fields
> fix: invoke correct fn on global extended connection/edge

- docs/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
In the ContextType Object, the value of `export` should be `Context` instead of `ContextModule` (see Line 133)
On line 62, the name of the exported interface is `Context`.
I have noticed that autocompletion of Prisma doesn't work because of the misspelling :)
When I checked the repository of the tutorial the value of `export` was correct.
https://github.com/graphql-nexus/tutorial/blob/e7a1988eded47a818398d14d823e45423ddeb3dd/api/schema.ts#L12
> chore(docs): Correct an object's value in the tutorial

- docs/content/040-adoption-guides/020-nexus-framework-users.mdx
asNexusMethod should also be imported in order to be used with graphql-scalars
> chore(docs): asNexusMethod import is missing

- docs/content/010-getting-started/03-tutorial/06-chapter-5-persisting-data-via-prisma.mdx
The prisma/cli has been renamed prisma, although the tutorial works fine if you install the prisma/cli this wont be the case forever. best update the docs now to avoid future confusion
> chore(docs): Updated tutorial docs (chapter 5 persisting-data-via-prisma) to fix cli install instructions

- src/plugins/connectionPlugin.ts
- tests/plugins/connectionPlugin.spec.ts
Just encountered a pretty bad bug with the connection plugin:
```ts
for (let i = 0; i < args.first; i++) {
if (i < nodes.length) {
cb(nodes[i], i)
}
}
```
This loop doesn't break if there's fewer nodes than `args.first`, so if you set `args.first` to something massive, it's going to iterate that many times.
Along with that, having a backward pagination with an amount larger than nodes will return incorrect values. Fixes & tests for both, without any changes to public APIs or existing tests.
> fix: reduce iteration in connections

- docs/content/015-api/010-object-type.mdx
Looks like there should only be a single argument passed to `objectType`.
> chore(docs): update 010-object-type.mdx

- docs/content/015-api/070-make-schema.mdx
Looks like the previous link points to a branch `develop` that no longer exists.
> chore(docs): fix broken link in 070-make-schema.mdx

- src/definitions/nonNull.ts
Ran into an issue around the generated return type for `nonNull()`, which produces:
```ts
NexusNonNullDef<any> | (TypeName & GraphQLNonNull<any>)
```
This is problematic when you reach a decent amount of types, where you'll hit a `union type that is too complex to represent` error. Removing the right hand side of the clause resolves the issue, and the fact that it's a `GraphQLNonNull` type is irrelevant, so we can just cast it to `NexusNonNullDef<any>` here
> fix: cast NexusNonNullDef to prevent union type complexity error

- examples/star-wars/package.json
ts-node-dev will not start the process if --transpileOnly is passed as it is deprecated.
> chore(docs): Change --transpileOnly to --transpile-only from star-wars example

- docs/content/015-api/070-make-schema.mdx
Well, according to the example shown [here](https://nexusjs.org/docs/api/make-schema#shouldgenerateartifacts-outputs-sourcetypes), the `contextType` attribute definition has been expecting to be passed inside of the attribute `sourceTypes` on `makeSchema`, But it doesn't work because the actually right place to use that should be directly on `makeSchema`, as such the own type definitions are expecting:
https://github.com/graphql-nexus/nexus/blob/5056129b4070c5ceb8a2a2e7c6244e01f0b9c897/src/builder.ts#L245
I didn't find any issue related to that, so I decided to create the PR directly without creating a new issue, just because it doesn't seem to be a big problem to be additionally discussed in another place, as long as it's not a big deal for the maintainers. But either way, I'm not quite …
> chore(docs): Obsolete example of using a custom typing to GraphQL context value on makeSchema API

- docs/src/components/layout.css
Minor fix for indentation issue mentioned in issue #849
> chore(docs): Resolve bullet indentation issue

- docs/content/014-guides/020-schema.mdx
Nexus nullability defaults to that everything is null by default. It's kind of the opposite is done here
> chore(docs): Nexus nullability defaults to that everything is null by default

- docs/content/030-plugins/050-prisma/030-api.mdx
As of now, the new Prisma docs aren't availible on the GitHub anymore, and we have to go on the official Prisma website. This replaces the GitHub file link with the link on the official Prisma website.
> chore(docs): update API link to Prisma object modeling 

- docs/content/015-api/100-query-field.mdx
Change the variable name appropriately in the example code
https://nexusjs.org/docs/api/query-field
> chore(docs): fix proper variable name

- src/builder.ts
- src/definitions/enumType.ts
- src/utils.ts
Closes #455
I added in a new `isArray` util which just calls `Array.isArray` but correctly narrows the type of the input. This is to workaround the issue described [here](https://github.com/microsoft/TypeScript/issues/17002), the solution was taken from the since reverted https://github.com/microsoft/TypeScript/pull/39258
> feat: Accept `ReadonlyArray<T>` for enum members

- src/plugins/connectionPlugin.ts
Needs a test, but currently the resolved value for `nodes` is incorrect if you specify a custom type for the connection edge.
> fix: correct edge node typing

- docs/content/015-api/070-make-schema.mdx
Added missing example for formatTypegen method.
It all started here: https://github.com/graphql-nexus/nexus/issues/926
> chore(docs): add formatTypegen example

- src/definitions/list.ts
- src/definitions/nonNull.ts
- src/definitions/nullable.ts
- tests/definitions/nexusMeta.spec.ts
Continuing on #934, allows meta types to be used within type wrappers
> fix: Allow meta types to be wrapped with null/list

- docs/content/015-api/030-scalar-type.mdx
I was messing around for ours to get a custom scalar working. I simply forgot to list in in the `types` array while creating the schema. There was no mention about this in the docs.
Thanks!
> chore(docs): improve scalar documentation

- patches/prettier-plugin-jsdoc+0.2.5.patch
- src/typegenPrinter.ts
- tests/__snapshots__/typegenPrinter.spec.ts.snap
- tests/integrations/kitchenSink/__typegen.ts
- tests/typegen/types.gen.ts
Reverts graphql-nexus/nexus#965
See comment in: https://github.com/graphql-nexus/nexus/issues/921#issuecomment-892998307
Need to check this again & think through the intended behavior, since I believe these types are primarily used for the `args` provided to a resolver, and if a default value is supplied it should exist on the args.
> revert: "fix: #921 wrong typegen for nullable values w/ default"

- src/definitions/definitionBlocks.ts
Fix plugins' `inputFieldDefTypes` not being propagated to CommonInputFieldConfig types. I've left the probably errorneous `NexusGenPluginFieldConfig` in for backward compatibility.
> fix: plugin inputFieldDefTypes

- src/makeSchema.ts
- src/typegenMetadata.ts
- src/typegenPrinter.ts
- src/typegenUtils.ts
- tests/__snapshots__/typegenPrinterGlobals.spec.ts.snap
- tests/backingTypes.spec.ts
- tests/typegenPrinter.spec.ts
Ensure that unused imports are not printed when splitting global & types files.
> fix: printer imports, follow up from #967

- examples/kitchen-sink/src/index.ts
- src/builder.ts
- src/typegenMetadata.ts
- tests/__snapshots__/typegenPrinterGlobals.spec.ts.snap
- tests/integrations/declarativeWrappingPlugin/__typegen.ts
- tests/integrations/kitchenSink/__typegen.ts
- tests/typegen/types.gen.ts
Continuing to iterate on changes from #967 
The current new behavior would technically be a breaking change if it's defaulted to `true`, since it'd export more types which could conflict with existing types if you're doing `export *` from the typegen file. Also have plans to refine the typegen a bit more before it ships.
> fix: revert typegen.declareInputs default to false

- src/builder.ts
- tests/__snapshots__/builder.spec.ts.snap
- tests/builder.spec.ts
Adds `config. schemaRoots` to `makeSchema`, providing the ability to configure the root `query` / `mutation` / `subcription` schema types.
Closes #867
> feat: ability to rename root types

- docs/content/010-getting-started/03-tutorial/02-chapter-1-setup-and-first-query.mdx
- docs/content/010-getting-started/03-tutorial/05-chapter-4-testing-your-api.mdx
- docs/content/010-getting-started/03-tutorial/06-chapter-5-persisting-data-via-prisma.mdx
- docs/content/010-getting-started/03-tutorial/07-chapter-6-testing-with-prisma.mdx
- docs/content/030-plugins/050-prisma/010-overview.mdx
- docs/content/040-adoption-guides/020-nexus-framework-users.mdx
- docs/content/040-adoption-guides/030-neuxs-framework-prisma-users.mdx
- docs/content/index.mdx
Noticed the npm add command while reading the docs and I thought maybe it was a little confusion with yarn add. So I wanted to help change it back to npm install.
> docs: change all "npm add" to "npm install"

- src/builder.ts
- src/definitions/wrapping.ts
- tests/plugins/nullabilityGuardPlugin.spec.ts
- tests/wrapping.spec.ts
> fix: Minimum GraphQL v16 support

- docs/content/010-getting-started/04-why-nexus.mdx
> chore(docs): fix typo 04-why-nexus.mdx

- docs/content/010-getting-started/03-tutorial/06-chapter-5-persisting-data-via-prisma.mdx
Fixed the typos where `draftToPublish` (used in the previous example) were mistakenly written as `postToPublish` which might lead to confusion for some readers.
> Fixed typos

- src/definitions/_types.ts
- tests/makeSchema.spec.ts
- tests/typegenPrinterGlobals.spec.ts
One last check to ensure v16 is good
> chore: add test confirming v16 schema compat

- src/builder.ts
Update comment to reflect the current behavior as per [`src/typegenUtils.ts`](https://github.com/graphql-nexus/nexus/blob/bc12ca0f8e704de0b7e911fa6352e8f2bb48cb22/src/typegenUtils.ts#L11). Ideally this behavior would be updated to reflect the original comment as most use cases won't need artifacts generated outside of `development`, but that would introduce a breaking change so probably needs to wait for a major release.
> docs: Update comment for `shouldGenerateArtifacts`

- docs/content/030-plugins/01-connection.mdx
- examples/kitchen-sink/kitchen-sink-schema.graphql
- src/plugins/connectionPlugin.ts
- tests/integrations/kitchenSink/__schema.graphql
- tests/plugins/__snapshots__/connectionPlugin.spec.ts.snap
As I brought up in #1069 we'd prefer not to have the word `facebook` in our publicly available schema. @tgriesser asked if changing the links to `relay.dev` was acceptable and we agreed it was. This PR simply changes any `facebook.github.io` links to their respective `relay.dev` links. `facebook.github.io/relay` already redirects to `relay.dev` so this should essentially be a no op from a documentation perspective.
> chore: change facebook.github.io to relay.dev links

- src/plugins/connectionPlugin.ts
- tests/plugins/connectionPlugin.spec.ts
The logic for backward pagination for the `connectionPlugin` is incorrect, given a list of items returned from `nodes`:
```
[1, 2, 3]
```
`last: 2` was returning `1, 2` rather than `2, 3`, which is incorrect based on the relay spec.
Adds `startOffset` calculated based on 
```ts
Math.max(nodes.length - args.last, 0)
``` 
to ensure the last nodes are returned. Also updates the logic to permit backward pagination on fixed-length lists without a custom backward pagination cursor.
> fix: incorrect logic for nodes in backward pagination

- src/definitions/directive.ts
This was generating the wrong type `string[]` which meant typesafety was lost on the `locations` for a `directive(` added in #952
> fix: add missing as const on the RequestDirectiveLocation

- src/builder.ts
- src/makeSchema.ts
- src/typegenMetadata.ts
We don't know if this is true until the schema is constructed, simpler to have a single path for printing schemas, that way we can make sure we're up-to-date with the latest in graphql-js, instead of having the internal SDL printer diverge
More follow up from #952
> fix: remove hasSDLDirectives internal state

- src/definitions/definitionBlocks.ts
- src/extensions.ts
- src/typegenPrinter.ts
- tests/integrations/kitchenSink/__app.ts
- tests/integrations/kitchenSink/__schema.graphql
- tests/integrations/kitchenSink/__typegen.ts
- tests/interfaceType.spec.ts
Fixes: #1006, #1003
For situations where we want to ensure that a type exists for a field, even when the field is derived via a `resolver`, this PR adds a `sourceType`. This fixes a longstanding complaint/source of confusion for Nexus about fields that have a resolver, where we still expect the field to exist in the `source`.
Old:
```ts
t.nonNull.id('id', {
// previously this would be undefined, unless you had a custom `sourceType` on the type-level which defined `id`
resolve: (source, args, ctx, info) => `${info.parentType.name}:${source.id}` 
})
```
New:
```ts
t.nonNull.id('id', {
resolve: (source, args, ctx, info) => `${info.parentType.name}:${source.id}`,
sourceType: 'number' // ensures that `source.id` exists as a `number` field on the generated backing source type
})
```
The API …
> feat: add sourceType option to fieldDefinition

- .gitignore
- package.json
- src/node.ts
- src/typegenAutoConfig.ts
- src/typegenFormatPrettier.ts
- src/typegenMetadata.ts
- src/typegenUtils.ts
- src/utils.ts
- tests/esm/esm-entry.js
- tests/esm/standalone.spec.ts
- yarn.lock
Closes #1028
- Removes top-level node imports (`fs`, `path`, `util`)
- Adds conditional flow to ensure these aren't required top-level anywhere when `process` doesn't exist
- Adds test that an `esbuild` script will execute in a VM, where node's require is unavailable
This should make it easier to run Nexus in Cloudflare workers - might not won't work with wrangler2 out of the box without `node_compat = true` b/c it's not as configurable, but should work well with miniflare & a custom esbuild similar to what I added in the test case. 
The codegen should be run separately as a node-script during development for the type-checking, will be opening a separate PR with a helper CLI for that, something like `$ nexus codegen`
> feat: better esm support, remove top-level node imports
