- docs/getting-started.md
- examples/ghost/src/schema/Query.ts
- src/typegenTypeHelpers.ts
> Fix boolean return typing, getting started example

- website/playground/Converter.tsx
- website/playground/fetchSchema.ts
- website/static/css/custom.css
> Add url input to SDL Converter

- examples/kitchen-sink/package.json
- src/builder.ts
- src/definitions/_types.ts
- src/definitions/definitionBlocks.ts
- src/definitions/objectType.ts
- src/definitions/subscriptionField.ts
Interested to get feedback on the implementation here, it works slightly differently than the other types  since subscription has different semantics:
TODO:
> Add subscriptionField, initial pass at #21

- src/typegenMetadata.ts
> fix mkdir throwing on node 10.9 below

- examples/githunt-api/yarn.lock
- examples/star-wars/yarn.lock
- src/builder.ts
- src/definitions/definitionBlocks.ts
- src/definitions/extendInputType.ts
- src/definitions/extendType.ts
- src/dynamicMethod.ts
Per @Weakky request for nexus-prisma
> Pass typeName to dynamic fields

- .gitignore
- src/builder.ts
- src/definitions/_types.ts
- src/definitions/definitionBlocks.ts
- src/definitions/wrapping.ts
- src/dynamicMethod.ts
- src/dynamicProperty.ts
- tests/typegen.spec.ts
Fixes #161
@schickling I believe this is the last piece you need in order to get nexus-prisma back on the main library, correct?
> Add dynamicObjectProperty, fix #161

- docs/database-access-with-prisma-v2.md
SQLite is also supported.
the current file list only
```
Prisma currently supports the following databases:
PostgreSQL
MySQL
```
> [Docs] database-access-with-prisma-v2.md

- docs/database-access-with-prisma-v2.md
👉 To be merged once we cut a new release of the prisma cli
> Update nexus-prisma documentation

- src/typegenMetadata.ts
> fix(typegen): delete prev file before writing next

- src/typegen.ts
- yarn.lock
Will close #241
~Will close #226~
> feat(deps): add support for TypeScript 3.6

- src/builder.ts
- src/dynamicMethod.ts
- src/dynamicProperty.ts
> Supply stage of builder execution to dynamics, fix #289

- website/playground/Playground.tsx
> chore(docs): Fix Broken Playground Page #330

- examples/kitchen-sink/package.json
- examples/kitchen-sink/src/index.ts
- examples/kitchen-sink/yarn.lock
> chore: Clarify ts-node example so it doesn't fail on run #327

- src/builder.ts
- tests/gh-issues/361-interfaceType-implements.spec.ts
- tests/inputObjectType.spec.ts
Fixes #361 
Looks like we weren't adding any interface references by default in the `.implements()`
> fix: #361, error when using interfaceType & implements

- src/plugins/connectionPlugin.ts
- src/typegenPrinter.ts
- src/typegenTypeHelpers.ts
Follow up on 6e39cebe27397e6601d546e65e3e438734be9e5b.
> fix: typegen always use manifest for package import

- src/plugins/connectionPlugin.ts
- src/typegenPrinter.ts
- src/typegenTypeHelpers.ts
- src/utils.ts
This simplifies the logic and makes it more generic.
> refactor: getOwnPackage util

- README.md
> chore(docs): fix typo on readme file

- package.json
- src/builder.ts
- src/plugins/connectionPlugin.ts
- src/plugins/fieldAuthorizePlugin.ts
- src/typegenFormatPrettier.ts
- src/typegenPrinter.ts
- src/utils.ts
- yarn.lock
This supports more prettier config scenarios. At least:
1. user is using extends feature of prettier
2. user is keeping prettier config inside package.json
> feat: use prettier api to load config

- .prettierrc
- examples/apollo-fullstack/src/typeDefs.ts
- examples/ghost/src/index.ts
- examples/kitchen-sink/src/example-plugins.ts
- examples/star-wars/src/data.ts
- examples/star-wars/src/index.ts
- examples/ts-ast-reader/src/index.ts
- package.json
- Keeps the prettier config local to the project (keeping at 110 to reduce diff, but will likely revert to 80)
- Format examples
> chore: Keep prettier config local to the project

- docs/content/010-getting-started/03-tutorial/05-chapter-4-testing-your-api.mdx
- docs/content/010-getting-started/03-tutorial/06-chapter-5-persisting-data-via-prisma.mdx
- Fix typo in `05-chapter-4-testing-your-api.mdx`
- Remove `experimental` text of prisma studio because it is stable now.
> chore(docs): Update docs content

- docs/content/010-getting-started/03-tutorial/02-chapter-1-setup-and-first-query.mdx
> chore(docs): fix typo in 02-chapter-1-setup-and-first-query docs

- docs/content/010-getting-started/03-tutorial/07-chapter-6-testing-with-prisma.mdx
Update post query due to latest Prisma Client which of version is `2.8.0`.
> chore(docs): Fix a prisma client call b/c latest Prisma Client

- docs/content/010-getting-started/03-tutorial/02-chapter-1-setup-and-first-query.mdx
- docs/content/014-guides/05-generated-artifacts.mdx
- docs/content/015-api/070-make-schema.mdx
- examples/ghost/README.md
- src/builder.ts
- src/typegenMetadata.ts
Fixes https://github.com/graphql-nexus/schema/issues/518.
> chore(docs): fix for outdated prisma-labs link in the documentation #518

- src/typegenPrinter.ts
Broken, due to absolute windows paths starting with the drive
> fix: Fixes broken windows tests

- docs/content/index.mdx
Use "@nexus/schema" as npm package instead of "nexus"
> chore(docs): fix installation note

- docs/content/030-pluginss/050-prisma/030-api.mdx
Relates to https://github.com/graphql-nexus/nexus-plugin-prisma/pull/923
> chore(docs): nexus plugin prisma for prisma v2.11

- docs/content/030-pluginss/050-prisma/010-overview.mdx
> docs: fix typo

- src/builder.ts
- src/definitions/args.ts
- src/plugin.ts
- src/typegenPrinter.ts
- src/typegenTypeHelpers.ts
- tests/__snapshots__/backingTypes.spec.ts.snap
- tests/__snapshots__/plugin.spec.ts.snap
- tests/__snapshots__/typegenPrinter.spec.ts.snap
- tests/plugin.spec.ts
- tests/plugins/__snapshots__/fieldAuthorizePlugin.spec.ts.snap
- tests/plugins/__snapshots__/queryComplexityPlugin.spec.ts.snap
> feat(plugin): add onFieldDefinition / onArgDefinition / onInputFieldDefinition

- src/builder.ts
- src/definitions/wrapping.ts
- src/utils.ts
Minor, noticed these maybe were better placed in `wrapping.ts` than `utils.ts`
> refactor: move wrapping helper fns to definitions/wrapping.ts

- CHANGELOG.md
@jasonkuhrt is there a way we can automate this?
> chore: Add release changelog entries to CHANGELOG.md

- docs/content/030-pluginss/050-prisma/010-overview.mdx
- docs/content/030-pluginss/050-prisma/030-api.mdx
Related to this PR: https://github.com/graphql-nexus/nexus-plugin-prisma/pull/899
> chore(docs): add atomicOperations setting for prisma plugin

- src/messages.ts
- src/sdlConverter.ts
- tests/__snapshots__/sdlConverter.spec.ts.snap
> fix: SDL converter list/nonNull chaining

- src/plugins/connectionPlugin.ts
- tests/plugins/__snapshots__/connectionPlugin.spec.ts.snap
- tests/plugins/connectionPlugin.spec.ts
> fix: #670 - explicit nullability for connectionPlugin

- docs/content/index.mdx
> docs: Update index.mdx, add missing list import

- src/definitions/definitionBlocks.ts
- src/plugin.ts
- src/plugins/declarativeWrappingPlugin.ts
- src/typegenPrinter.ts
- src/typegenTypeHelpers.ts
- tests/__snapshots__/backingTypes.spec.ts.snap
- tests/__snapshots__/typegenPrinter.spec.ts.snap
- tests/integrations/abstractTypes/allStrategiesOptionalWhenTypeNameEnabled/__typegen.ts
- tests/integrations/abstractTypes/isTypeOfsImplemented/__typegen.ts
- tests/integrations/abstractTypes/missingIsTypeOf/__typegen.ts
- tests/integrations/abstractTypes/missingResolveType/__typegen.ts
- tests/integrations/abstractTypes/missingResolveTypeOrIsTypeOf/__typegen.ts
- tests/integrations/abstractTypes/missingTypenameDiscriminant/__typegen.ts
- tests/integrations/abstractTypes/resolveTypeImplemented/__typegen.ts
- tests/integrations/declarativeWrappingPlugin/__app.ts
- tests/integrations/declarativeWrappingPlugin/__typegen.ts
- tests/integrations/kitchenSink/__typegen.ts
- tests/integrations/unionTooComplexToRepresent/__typegen.ts
- tests/plugins/__snapshots__/fieldAuthorizePlugin.spec.ts.snap
- tests/plugins/__snapshots__/queryComplexityPlugin.spec.ts.snap
- tests/typegen/types.gen.ts
> fix: #618 Add inputFieldDefTypes for declarativeWrappingPlugin

- docs/content/014-guides/020-schema.mdx
- docs/content/030-plugins/01-connection.mdx
- docs/content/030-plugins/05-nullability-guard.mdx
- docs/content/030-plugins/050-prisma/030-api.mdx
- docs/package.json
- docs/src/components/header.tsx
- docs/src/components/layout.tsx
- docs/src/components/toc.tsx
- docs/src/components/topSection.tsx
- docs/src/interfaces/Article.interface.ts
- docs/src/layouts/articleLayout.tsx
- docs/src/utils/stickWhenNeeded.ts
- docs/yarn.lock
Dunno what I was thinking to put "nested wrapping" as commit name 🤦 
- `stickWhenNeeded` helper was taken from `prisma/docs`
> docs: add sticky table of content

- docs/content/040-adoption-guides/030-neuxs-framework-prisma-users.mdx
- src/definitions/_types.ts
- src/definitions/definitionBlocks.ts
- src/definitions/extendType.ts
- src/definitions/objectType.ts
> docs: cover the output type builder api with jsdoc

- src/sdlConverter.ts
- tests/v15/__snapshots__/sdlConverter.spec.ts.snap
- tests/v15/sdlConverter.spec.ts
#496 added support for interfaces implementing interfaces, but these changes were not reflected in the SDL converter. This PR adds support for that there as well :)
> feat: add support for interfaces implementing interfaces to sdlConverter

- src/sdlConverter.ts
- tests/__snapshots__/sdlConverter.spec.ts.snap
Fixes the following issues: 
* Missing end parenthesis on scalar arguments
* Missing comma after each argument
* Missing argument default values
* Wrapped field types had invalid type argument
* Inconsistent syntax for wrapped field types
> SDLConverter fixes

- docs/content/010-getting-started/03-tutorial/02-chapter-1-setup-and-first-query.mdx
- docs/content/010-getting-started/03-tutorial/03-chapter-2-writing-your-first-schema.mdx
closes #753
Warn user of type error, fix grammar, and make a diff code block for the additional npm scripts because (at least for me) npm init -y includes a "test" script.
> chore(docs): Small changes to docs

- docs/content/015-api/010-object-type.mdx
`StatusEnum` variable is not being used
> chore(docs): Update 010-object-type.mdx

- docs/content/030-plugins/050-prisma/010-overview.mdx
From: It gives you an API you to project fields from models defined in your Prisma schema
To: It gives you an API ~~you~~ to project fields from models defined in your Prisma schema
> chore(docs): Fix typo in About section

- docs/content/010-getting-started/03-tutorial/05-chapter-4-testing-your-api.mdx
Change 'false' to 'true' in line 288
> chore(docs): Update 05-chapter-4-testing-your-api.mdx

- docs/content/030-plugins/03-field-authorize.mdx
Added some getting started information and a description of the field this plugin adds.
works #549
> docs: add more information to field authorize plugin

- docs/content/015-api/061-list-nonNull.mdx
It was open, so I blocked it. :)
> chore(docs): Fix Docs 061-list-nonNull.mdx

- docs/content/010-getting-started/03-tutorial/01-chapter-0-introduction.mdx
- docs/content/010-getting-started/03-tutorial/02-chapter-1-setup-and-first-query.mdx
- docs/content/010-getting-started/03-tutorial/03-chapter-2-writing-your-first-schema.mdx
- docs/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
- docs/content/010-getting-started/03-tutorial/05-chapter-4-testing-your-api.mdx
- docs/content/010-getting-started/03-tutorial/06-chapter-5-persisting-data-via-prisma.mdx
- docs/content/010-getting-started/03-tutorial/07-chapter-6-testing-with-prisma.mdx
- added snippets copy
- moved `app.ts` contents to `server.ts` (Updated package.json).`
- migrated from Postgres to SQLite
-fixed tests 🤞🏽
> chore(docs): Updated getting started tutorial

- docs/content/030-plugins/050-prisma/010-overview.mdx
updated `introspect` and `@prisma/cli` references.
> fix(docs): updated prisma references

- docs/content/010-getting-started/03-tutorial/03-chapter-2-writing-your-first-schema.mdx
> fix: Broken Link in Tutorial Chapter 2

- docs/content/010-getting-started/03-tutorial/02-chapter-1-setup-and-first-query.mdx
- docs/content/010-getting-started/03-tutorial/04-chapter-3-adding-mutations-to-your-api.mdx
- docs/content/010-getting-started/03-tutorial/05-chapter-4-testing-your-api.mdx
> fix(docs): updated test script and server start

- src/typegenUtils.ts
…ather than only when in development
#883
> fix: sync should gen artifact logic with what docs say

- tests/backingTypes.spec.ts
#887 was merged with failing tests, now the main branch is also failing.
> chore(tests): update snapshots that were forgotten in #887

- src/builder.ts
- src/core.ts
- src/index.ts
- src/makeSchema.ts
- src/utils.ts
- tests/makeSchema.spec.ts
Minor, but thought this was simpler when coming back to the codebase after awhile
> refactor: move makeSchema into separate file from builder

- src/builder.ts
> refactor: remove duplicate core schema type checks

- docs/content/010-getting-started/03-tutorial/07-chapter-6-testing-with-prisma.mdx
> chore(docs): fix typo in 07-chapter-6-testing-with-prisma.mdx

- docs/content/010-getting-started/03-tutorial/05-chapter-4-testing-your-api.mdx
> chore(docs): fix typo 05-chapter-4-testing-your-api.mdx

- docs/content/040-adoption-guides/030-neuxs-framework-prisma-users.mdx
> chore(docs): fix typo 030-neuxs-framework-prisma-users.mdx

- src/builder.ts
It looks like the stream/defer is feature-flagged with an option on the GraphQLSchema config:
https://github.com/robrichard/defer-stream-wg/discussions/12
This PR allows for specifying any options defined on the schema which don't conflict with our internal definitions directly on `makeSchema`
> feat: allow specifying custom directives in makeSchema
